// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlZEX7LgZXmHrENKD3mFgAQg9KakncI0',
    appId: '1:361893552986:web:f8d995a45c8b22bec88963',
    messagingSenderId: '361893552986',
    projectId: 'phone-auth-69a04',
    authDomain: 'phone-auth-69a04.firebaseapp.com',
    storageBucket: 'phone-auth-69a04.firebasestorage.app',
    measurementId: 'G-25GSF57WSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCynMkKRMFnDtfLRNzk6_gdvLEC3BwBa38',
    appId: '1:361893552986:android:310e6036f685106dc88963',
    messagingSenderId: '361893552986',
    projectId: 'phone-auth-69a04',
    storageBucket: 'phone-auth-69a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-bovCHavNp3PtqNmUQEx42g-Xl0tDORA',
    appId: '1:361893552986:ios:5c74de23123395a3c88963',
    messagingSenderId: '361893552986',
    projectId: 'phone-auth-69a04',
    storageBucket: 'phone-auth-69a04.firebasestorage.app',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-bovCHavNp3PtqNmUQEx42g-Xl0tDORA',
    appId: '1:361893552986:ios:5c74de23123395a3c88963',
    messagingSenderId: '361893552986',
    projectId: 'phone-auth-69a04',
    storageBucket: 'phone-auth-69a04.firebasestorage.app',
    iosBundleId: 'com.example.phoneAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmlZEX7LgZXmHrENKD3mFgAQg9KakncI0',
    appId: '1:361893552986:web:f4017cc8f16dced5c88963',
    messagingSenderId: '361893552986',
    projectId: 'phone-auth-69a04',
    authDomain: 'phone-auth-69a04.firebaseapp.com',
    storageBucket: 'phone-auth-69a04.firebasestorage.app',
    measurementId: 'G-RJYT9Y6W9W',
  );
}
